### PR TITLE
Adding support for SNI

### PR DESCRIPTION
**Pull request by jamiephill**
Please consider adding these changes to support SNI to your module.

### CODE REVIEW

**Comment by hirose31** [comment]
This module already supports SNI.

Could you show me the code that does not work as expected?

**Comment by jamiephill** [comment]
By looking at the documentation, I didn't see a way to specify a host that was different from the SNI.  For instance, we have two proxy servers proxy-01.example.com and proxy-02.example.com that handle multiple sites with different certificates.  So I needed a way to specify connect to host proxy-01.example.com, but get the certificate for site1.example.com, site2.example.com, etc.

If that can already be done great (and if so can you tell me how?).  If not, what I did was add a way to specify a name for the client hello that differs from the hostname being connected to.

Thanks.

**Comment by hirose31** [comment]
I understood clearly. I will merge your PR and relase new version.

Thanks!

**Comment by hirose31** [comment]
I've just released v1.23, it will be soon available.

**Pull request merged**
